[package]
name = "rule_executor"
version = "0.1.0"
authors = ["Tony Riemer <driemworks@idealabs.network>"]
edition = "2021"
rust-version = "1.56.1"

[dependencies]
ink_primitives = { version = "3.0.0", default-features = false }
ink_metadata = { version = "3.0.0", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0", default-features = false }
ink_storage = { version = "3.0.0", default-features = false }
ink_lang = { version = "3.0.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0.0", default-features = false, features = ["derive"], optional = true }
# limited_use_contract = { path = "../composable_access_rules/limited_use", default-features = false, features=["ink-as-dependency"] }

[lib]
name = "rule_executor"
path = "lib.rs"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
]
ink-as-dependency = []
